### ISSUE TITLE
When trying to play two sounds at one time ftrobopy prints errors

### ISSUE THREAD

**Issue by ski7777** [ftrobopy/ftrobopy#17]
If I try to play a second sound while the first one is still playing I got this:
```
Traceback (most recent call last):
  File "/home/raphael/ftcommunity-TXT/output/target/usr/lib/python3.5/site-packages/serial/serialposix.py", line 464, in read
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/raphael/ftcommunity-TXT/output/target/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
  File "/home/raphael/ftcommunity-TXT/output/target/usr/lib/python3.5/site-packages/ftrobopy.py", line 1562, in run
  File "/home/raphael/ftcommunity-TXT/output/target/usr/lib/python3.5/site-packages/serial/serialposix.py", line 475, in read
serial.serialutil.SerialException: read failed: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
```

**Comment by ski7777** [comment]
Now I am sure this is not a problem by playing two sounds at one time but I am not sure when this happens.
