### ISSUE TITLE
Keine Werte bei getPower und getTemperatur

### ISSUE THREAD

**Issue by kseidenschnur** [ftrobopy/ftrobopy#36]
Wenn ich getPower oder getTemperatur im direct Modus ausführe bekomme ich folgende Meldung:

Connected to  TXT direct firmware version not detected
Traceback (most recent call last):
  File "/home/ftc/direct-test2.py", line 7, in <module>
    temperatur = txt.getTemperature()
  File "/usr/lib/python3.9/site-packages/ftrobopy.py", line 1630, in getTemperature
AttributeError: 'ftrobopy' object has no attribute '_use_TransferMode'

Habe in der ftrobopy '_use_TransferMode' für getPower und getTemperatur in '_use_TransferAreaMode' geändert.

Nun bekomme ich keine Fehlermeldung mehr, aber ich bekomme für beide Werte nur eine 0 zurück.

Hier mein Code:

import ftrobopy
txt=ftrobopy.ftrobopy('auto')

temperatur = txt.getTemperature()
print(temperatur)
spannung = txt.getPower()
print(spannung)

**Comment by ftrobopy** [comment]
fixed
